"""schema initial

Revision ID: a6de8f2759b3
Revises:
Create Date: 2026-09-18 20:57:42.193080+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from choregos_api.db.base import Json

revision: str = "a6de8f2759b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


RLS_TABLES = (
    "projects",
    "connectors",
    "workflow_defs",
    "policies",
    "work_items",
    "runs",
    "human_requests",
    "events",
    "findings",
    "releases",
    "cost_ledger",
    "memory_facts",
)


def _enable_rls() -> None:
    """RLS PostgreSQL : une organisation ne voit jamais les lignes d'une autre (§1.3).

    La politique s'appuie sur `app.current_org`, posé par `session_scope(org_slug=…)`.
    """
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        """
        CREATE OR REPLACE FUNCTION choregos_current_org() RETURNS text AS $$
          SELECT current_setting('app.current_org', true)
        $$ LANGUAGE sql STABLE;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION choregos_project_org(pid text) RETURNS text AS $$
          SELECT o.slug FROM projects p JOIN organizations o ON o.id = p.org_id WHERE p.id = pid
        $$ LANGUAGE sql STABLE;
        """
    )
    for table in RLS_TABLES:
        column = "id" if table == "projects" else "project_id"
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_org_isolation ON {table}
            USING (
              choregos_current_org() IS NULL
              OR choregos_project_org({column}) = choregos_current_org()
            )
            """
        )


def _disable_rls() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_backends",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("capabilities", Json(), nullable=False),
        sa.Column("conformance", Json(), nullable=False),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_backends")),
    )
    op.create_index(op.f("ix_agent_backends_name"), "agent_backends", ["name"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("actor_id", sa.String(length=200), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("payload", Json(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "executors",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cluster", sa.String(length=128), nullable=True),
        sa.Column("namespace_pattern", sa.String(length=128), nullable=True),
        sa.Column("runner_image", sa.String(length=255), nullable=True),
        sa.Column("default_timeout_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executors")),
    )
    op.create_index(op.f("ix_executors_kind"), "executors", ["kind"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("settings", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "templates",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("manifest", Json(), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("name", "version", name="template_name_version"),
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("oidc_sub", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_service", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_oidc_sub"), "users", ["oidc_sub"], unique=True)
    op.create_table(
        "webhook_deliveries",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("delivery_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_digest", sa.String(length=80), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
        sa.UniqueConstraint("source", "delivery_id", name="source_delivery"),
    )
    op.create_index(op.f("ix_webhook_deliveries_source"), "webhook_deliveries", ["source"], unique=False)
    op.create_table(
        "api_tokens",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("hash", sa.String(length=128), nullable=False),
        sa.Column("scopes", Json(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
    )
    op.create_index(op.f("ix_api_tokens_hash"), "api_tokens", ["hash"], unique=True)
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("template_ref", sa.String(length=128), nullable=True),
        sa.Column("config", Json(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provision_state", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_projects_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("org_id", "slug", name="org_slug"),
    )
    op.create_index(op.f("ix_projects_org_id"), "projects", ["org_id"], unique=False)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "connectors",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("config", Json(), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_connectors_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
        sa.UniqueConstraint("project_id", "kind", name="project_kind"),
    )
    op.create_index(op.f("ix_connectors_project_id"), "connectors", ["project_id"], unique=False)
    op.create_table(
        "gateway_keys",
        sa.Column("key_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("budget_usd", sa.Float(), nullable=False),
        sa.Column("spend_usd", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_gateway_keys_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_keys")),
    )
    op.create_index(op.f("ix_gateway_keys_key_id"), "gateway_keys", ["key_id"], unique=True)
    op.create_index(op.f("ix_gateway_keys_project_id"), "gateway_keys", ["project_id"], unique=False)
    op.create_index(op.f("ix_gateway_keys_run_id"), "gateway_keys", ["run_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_memberships_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("user_id", "org_id", "project_id", name="user_org_project"),
    )
    op.create_index(op.f("ix_memberships_org_id"), "memberships", ["org_id"], unique=False)
    op.create_index(op.f("ix_memberships_project_id"), "memberships", ["project_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "memory_facts",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance", Json(), nullable=False),
        sa.Column("proposed_by", sa.String(length=200), nullable=True),
        sa.Column("embedding", Json(), nullable=True),
        sa.Column("paths", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_memory_facts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_facts")),
    )
    op.create_index(op.f("ix_memory_facts_external_id"), "memory_facts", ["external_id"], unique=False)
    op.create_index(op.f("ix_memory_facts_kind"), "memory_facts", ["kind"], unique=False)
    op.create_index(op.f("ix_memory_facts_project_id"), "memory_facts", ["project_id"], unique=False)
    op.create_index(
        "ix_memory_facts_project_subject", "memory_facts", ["project_id", "subject"], unique=False
    )
    op.create_index(op.f("ix_memory_facts_status"), "memory_facts", ["status"], unique=False)
    op.create_table(
        "model_profiles",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("litellm_model", sa.String(length=200), nullable=False),
        sa.Column("params", Json(), nullable=False),
        sa.Column("validated_backends", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_model_profiles_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_profiles")),
    )
    op.create_index(op.f("ix_model_profiles_name"), "model_profiles", ["name"], unique=False)
    op.create_index(op.f("ix_model_profiles_project_id"), "model_profiles", ["project_id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("yaml", sa.Text(), nullable=False),
        sa.Column("json", Json(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_policies_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
    )
    op.create_index(op.f("ix_policies_is_active"), "policies", ["is_active"], unique=False)
    op.create_index(op.f("ix_policies_project_id"), "policies", ["project_id"], unique=False)
    op.create_table(
        "releases",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("env", sa.String(length=32), nullable=False),
        sa.Column("batch_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("items", Json(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("verdict", Json(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("promotion_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_releases_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_index("ix_releases_project_env", "releases", ["project_id", "env"], unique=False)
    op.create_index(op.f("ix_releases_project_id"), "releases", ["project_id"], unique=False)
    op.create_index(op.f("ix_releases_status"), "releases", ["status"], unique=False)
    op.create_table(
        "workflow_defs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("yaml", sa.Text(), nullable=False),
        sa.Column("json", Json(), nullable=False),
        sa.Column("checksum", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workflow_defs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_defs")),
        sa.UniqueConstraint("project_id", "name", "version", name="project_name_version"),
    )
    op.create_index(op.f("ix_workflow_defs_checksum"), "workflow_defs", ["checksum"], unique=False)
    op.create_index(op.f("ix_workflow_defs_is_active"), "workflow_defs", ["is_active"], unique=False)
    op.create_index(op.f("ix_workflow_defs_project_id"), "workflow_defs", ["project_id"], unique=False)
    op.create_table(
        "deployments",
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("env", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.String(length=128), nullable=True),
        sa.Column("cd_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_deployments_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
    )
    op.create_index(op.f("ix_deployments_release_id"), "deployments", ["release_id"], unique=False)
    op.create_table(
        "work_items",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("tracker_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body_snapshot", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("size", sa.String(length=4), nullable=True),
        sa.Column("risk", sa.String(length=8), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("workflow_def_id", sa.String(length=36), nullable=True),
        sa.Column("policy_id", sa.String(length=36), nullable=True),
        sa.Column("temporal_wf_id", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("allowed_paths", Json(), nullable=False),
        sa.Column("pr_url", sa.String(length=500), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("totals", Json(), nullable=False),
        sa.Column("documents", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["policies.id"], name=op.f("fk_work_items_policy_id_policies"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_work_items_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_def_id"],
            ["workflow_defs.id"],
            name=op.f("fk_work_items_workflow_def_id_workflow_defs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("project_id", "tracker_key", name="project_tracker_key"),
    )
    op.create_index(op.f("ix_work_items_project_id"), "work_items", ["project_id"], unique=False)
    op.create_index("ix_work_items_project_state", "work_items", ["project_id", "state"], unique=False)
    op.create_index(op.f("ix_work_items_state"), "work_items", ["state"], unique=False)
    op.create_index(op.f("ix_work_items_temporal_wf_id"), "work_items", ["temporal_wf_id"], unique=False)
    op.create_index(op.f("ix_work_items_tracker_key"), "work_items", ["tracker_key"], unique=False)
    op.create_table(
        "events",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("work_item_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("payload", Json(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_events_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_events_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_project_id"), "events", ["project_id"], unique=False)
    op.create_index("ix_events_project_ts", "events", ["project_id", "ts"], unique=False)
    op.create_index(op.f("ix_events_type"), "events", ["type"], unique=False)
    op.create_index(op.f("ix_events_work_item_id"), "events", ["work_item_id"], unique=False)
    op.create_table(
        "human_requests",
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("transition_id", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", Json(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=200), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision", Json(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_human_requests_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_human_requests_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_requests")),
    )
    op.create_index(op.f("ix_human_requests_project_id"), "human_requests", ["project_id"], unique=False)
    op.create_index(op.f("ix_human_requests_work_item_id"), "human_requests", ["work_item_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("transition_id", sa.String(length=64), nullable=True),
        sa.Column("stage_role", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("backend", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("executor_kind", sa.String(length=32), nullable=True),
        sa.Column("executor_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tokens", Json(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("gateway_key_id", sa.String(length=128), nullable=True),
        sa.Column("result", Json(), nullable=True),
        sa.Column("stage_input", Json(), nullable=True),
        sa.Column("transcript_url", sa.String(length=500), nullable=True),
        sa.Column("context_pack_url", sa.String(length=500), nullable=True),
        sa.Column("context_pack", Json(), nullable=True),
        sa.Column("playbook_checksum", sa.String(length=80), nullable=True),
        sa.Column("allowed_paths", Json(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_runs_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_runs_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_index("ix_runs_project_status", "runs", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_runs_stage_role"), "runs", ["stage_role"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_index(op.f("ix_runs_work_item_id"), "runs", ["work_item_id"], unique=False)
    op.create_table(
        "cost_ledger",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("backend", sa.String(length=64), nullable=True),
        sa.Column("stage_role", sa.String(length=32), nullable=True),
        sa.Column("size", sa.String(length=4), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("tokens_cached", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cost_eur", sa.Float(), nullable=False),
        sa.Column("fx_rate", sa.Float(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cost_ledger_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_cost_ledger_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_cost_ledger_work_item_id_work_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_ledger")),
    )
    op.create_index(op.f("ix_cost_ledger_project_id"), "cost_ledger", ["project_id"], unique=False)
    op.create_index("ix_cost_ledger_project_ts", "cost_ledger", ["project_id", "ts"], unique=False)
    op.create_index(op.f("ix_cost_ledger_run_id"), "cost_ledger", ["run_id"], unique=False)
    op.create_index(op.f("ix_cost_ledger_ts"), "cost_ledger", ["ts"], unique=False)
    op.create_index(op.f("ix_cost_ledger_work_item_id"), "cost_ledger", ["work_item_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("origin_work_item_id", sa.String(length=36), nullable=True),
        sa.Column("origin_run_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("estimate", sa.String(length=4), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_work_item_id", sa.String(length=36), nullable=True),
        sa.Column("duplicate_of", sa.String(length=36), nullable=True),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("relevant", sa.Boolean(), nullable=True),
        sa.Column("embedding", Json(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_work_item_id"],
            ["work_items.id"],
            name=op.f("fk_findings_created_work_item_id_work_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["origin_run_id"], ["runs.id"], name=op.f("fk_findings_origin_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["origin_work_item_id"],
            ["work_items.id"],
            name=op.f("fk_findings_origin_work_item_id_work_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_findings_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(op.f("ix_findings_project_id"), "findings", ["project_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("payload", Json(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="run_seq"),
    )
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    # ### end Alembic commands ###
    _enable_rls()


def downgrade() -> None:
    _disable_rls()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_project_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_cost_ledger_work_item_id"), table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_ts"), table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_run_id"), table_name="cost_ledger")
    op.drop_index("ix_cost_ledger_project_ts", table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_project_id"), table_name="cost_ledger")
    op.drop_table("cost_ledger")
    op.drop_index(op.f("ix_runs_work_item_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_stage_role"), table_name="runs")
    op.drop_index("ix_runs_project_status", table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_human_requests_work_item_id"), table_name="human_requests")
    op.drop_index(op.f("ix_human_requests_project_id"), table_name="human_requests")
    op.drop_table("human_requests")
    op.drop_index(op.f("ix_events_work_item_id"), table_name="events")
    op.drop_index(op.f("ix_events_type"), table_name="events")
    op.drop_index("ix_events_project_ts", table_name="events")
    op.drop_index(op.f("ix_events_project_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_work_items_tracker_key"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_temporal_wf_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_state"), table_name="work_items")
    op.drop_index("ix_work_items_project_state", table_name="work_items")
    op.drop_index(op.f("ix_work_items_project_id"), table_name="work_items")
    op.drop_table("work_items")
    op.drop_index(op.f("ix_deployments_release_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_workflow_defs_project_id"), table_name="workflow_defs")
    op.drop_index(op.f("ix_workflow_defs_is_active"), table_name="workflow_defs")
    op.drop_index(op.f("ix_workflow_defs_checksum"), table_name="workflow_defs")
    op.drop_table("workflow_defs")
    op.drop_index(op.f("ix_releases_status"), table_name="releases")
    op.drop_index(op.f("ix_releases_project_id"), table_name="releases")
    op.drop_index("ix_releases_project_env", table_name="releases")
    op.drop_table("releases")
    op.drop_index(op.f("ix_policies_project_id"), table_name="policies")
    op.drop_index(op.f("ix_policies_is_active"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_model_profiles_project_id"), table_name="model_profiles")
    op.drop_index(op.f("ix_model_profiles_name"), table_name="model_profiles")
    op.drop_table("model_profiles")
    op.drop_index(op.f("ix_memory_facts_status"), table_name="memory_facts")
    op.drop_index("ix_memory_facts_project_subject", table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_project_id"), table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_kind"), table_name="memory_facts")
    op.drop_index(op.f("ix_memory_facts_external_id"), table_name="memory_facts")
    op.drop_table("memory_facts")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_project_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_org_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_gateway_keys_run_id"), table_name="gateway_keys")
    op.drop_index(op.f("ix_gateway_keys_project_id"), table_name="gateway_keys")
    op.drop_index(op.f("ix_gateway_keys_key_id"), table_name="gateway_keys")
    op.drop_table("gateway_keys")
    op.drop_index(op.f("ix_connectors_project_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_org_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_hash"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_webhook_deliveries_source"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_users_oidc_sub"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_executors_kind"), table_name="executors")
    op.drop_table("executors")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_agent_backends_name"), table_name="agent_backends")
    op.drop_table("agent_backends")
    # ### end Alembic commands ###
