"""Cœur Choregos : domaine, DSL de workflow, politiques, gates, résolution de modèles.

Ce paquet ne fait **aucune** entrée/sortie : il est pur, typé strict et testable sans service.
Tout ce qui parle au monde extérieur vit dans `packages/adapters`.
"""

from __future__ import annotations

from .acces import Acces, RapportAcces, rapport_d_acces
from .catalogue import Catalogue, OutilCatalogue, charger_catalogue, construire_requete
from .domain import (
    Change,
    CiStatus,
    Comment,
    DiffFile,
    DiffSummary,
    ExecRef,
    ExecStatus,
    Fact,
    FindingRecord,
    GatewayModel,
    Health,
    LaunchContext,
    LaunchSpec,
    Memory,
    Message,
    MessageAction,
    NewItem,
    PromotionRef,
    Provenance,
    PrRef,
    PrState,
    ReleaseItem,
    ReleaseRecord,
    ReviewState,
    RolloutState,
    RunRecord,
    Spend,
    StageJobSpec,
    TrackerStateMapping,
    VirtualKey,
    Window,
    WorkItemData,
    aware,
    elapsed_seconds,
    utcnow,
)
from .dsl import (
    TEMPLATE_NAMES,
    Decision,
    ValidationReport,
    WorkflowEngine,
    checksum,
    dump_workflow,
    load_template,
    parse_workflow,
    parse_workflow_file,
    template_yaml,
    to_graph,
    to_mermaid,
    validate_workflow,
)
from .errors import (
    ChoregosError,
    GateError,
    Issue,
    ModelResolutionError,
    PolicyError,
    ValidationError,
)
from .gates import GateContext, GateOutcome, evaluate, is_async_gate, known_gates, matches_any, scan_secrets
from .models import (
    BY_SIZE_MAP,
    KNOWN_BACKEND_NAMES,
    ModelResolver,
    ResolvedModel,
    estimate_tokens,
)
from .policy import (
    PRESET_NAMES,
    ApprovalDecision,
    PolicyEngine,
    engine_for,
    load_preset,
    parse_policy,
    preset_yaml,
)

__version__ = "0.1.0"

__all__ = [
    "BY_SIZE_MAP",
    "KNOWN_BACKEND_NAMES",
    "PRESET_NAMES",
    "TEMPLATE_NAMES",
    "Acces",
    "ApprovalDecision",
    "Catalogue",
    "Change",
    "ChoregosError",
    "CiStatus",
    "Comment",
    "Decision",
    "DiffFile",
    "DiffSummary",
    "ExecRef",
    "ExecStatus",
    "Fact",
    "FindingRecord",
    "GateContext",
    "GateError",
    "GateOutcome",
    "GatewayModel",
    "Health",
    "Issue",
    "LaunchContext",
    "LaunchSpec",
    "Memory",
    "Message",
    "MessageAction",
    "ModelResolutionError",
    "ModelResolver",
    "NewItem",
    "OutilCatalogue",
    "PolicyEngine",
    "PolicyError",
    "PrRef",
    "PrState",
    "PromotionRef",
    "Provenance",
    "RapportAcces",
    "ReleaseItem",
    "ReleaseRecord",
    "ResolvedModel",
    "ReviewState",
    "RolloutState",
    "RunRecord",
    "Spend",
    "StageJobSpec",
    "TrackerStateMapping",
    "ValidationError",
    "ValidationReport",
    "VirtualKey",
    "Window",
    "WorkItemData",
    "WorkflowEngine",
    "aware",
    "charger_catalogue",
    "checksum",
    "construire_requete",
    "dump_workflow",
    "elapsed_seconds",
    "engine_for",
    "estimate_tokens",
    "evaluate",
    "is_async_gate",
    "known_gates",
    "load_preset",
    "load_template",
    "matches_any",
    "parse_policy",
    "parse_workflow",
    "parse_workflow_file",
    "preset_yaml",
    "rapport_d_acces",
    "scan_secrets",
    "template_yaml",
    "to_graph",
    "to_mermaid",
    "utcnow",
    "validate_workflow",
]
